### ISSUE TITLE
>>

### ISSUE THREAD

**Issue by steventheworker** [SoloUnity/macos-apps-and-enhancements#11]
<<

**Comment by SoloUnity** [comment]
Sorry, not trying to sound rude, but doesn't this app achieve the same thing as what's built in to the OS? You can accomplish more or less the same thing in Tinkertool via Tinkertool > Dock > Stacks > Use scroll wheel or scroll gesture to access contents, or via a terminal command. 

![image](https://user-images.githubusercontent.com/77747704/156288197-9253ff80-eecc-4e15-946e-8402120bf6b5.png)

**Comment by steventheworker** [comment]
Oh, is this what everyone uses to get window previews when they hover over a dock icon? I've never heard of it.
