### ISSUE TITLE
Add Dozer in Menu Bar Managers

### ISSUE THREAD

**Issue by asutoshvariar** [SoloUnity/macos-apps-and-enhancements#7]
Performs the same actions as Vanilla, but is FOSS. 

https://github.com/Mortennn/Dozer

**Comment by SoloUnity** [comment]
Unfortunately, it seems as if Dozer is longer actively maintained so I won’t add it the list. Hidden bar is a pretty good replacement though, and is also foss. https://github.com/dwarvesf/hidden
